[project]
name = "novaad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dasdias", email = "das.dias6@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "confz>=2.1.0",
    "docopt>=0.6.2",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pip>=25.3",
    "plotly>=6.5.1",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "scipy>=1.15.3",
    "toml>=0.10.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
